console.log("this is external javascript");

// var a=10;
// console.log(a);

// let b= 20;
// console.log(b);

// const c=30;
// console.log(c);



// if(a>10){
//     console.log("yeah a is greater");
// }
// else if(a==10){
//     console.log("yeah a is equal");
// }
// else{
//     console.log("yeah a is less");
// }

// switch(a){
//     case 1:console.log("first case");
//     break;
//     case 2:console.log("second case");
//     break;
//     default:console.log("default case");  
// }

let a=5;

while(a!=0){
    console.log("value of a->",a);
    a--;
}
console.log("successful");


// do{
//     console.log("ek baar to chalunga");
//         a++;
// }
// while(a=2){
//     console.log("kya hua");
// }